Couch-Coders/6th-camp_us-fe

- src/Components/Navbar/Navbar.js
- src/Components/Navbar/Navbar.styles.js
<br/>
- issue title  #16 
<br/>
- 로그인 / 로그아웃 / 아바타 / 마이페이지 디자인 수정
- (PC ver) 로그인된 상태일 떄, 아바타 클릭 시 하단에 마이페이지 및 로그아웃 버튼 표시
- (Mobile ver) 로그인된 상태일 때, 햄버거 메뉴 클릭 시 리스트 마지막에 노출
<br/>
- 모바일에서는 로그인 되어도 리스트에 아바타가 보이지 않도록 했습니다.
<br/>
> [#16]feature/header 아바타, 마이페이지, 로그아웃 디자인 및 위치 변경

- src/Components/Main/MainSearch/MainSearch.js
<br/>
- issue title  #2  
<br/>
- 검색영역 별점 selectbox에서 antd 별점 컴포넌트로 수정
<br/>
<br/>
> [#2]feature/main 검색영역 별점부분 수정

- src/Hooks/useGetGeolocation.jsx
- src/Pages/MainPage/MainPage.jsx
<br/>
- issue title  #48  
<br/>
- geolocation 함수 사용하여 사용자의 X, Y 좌표 찾음 
- X,Y 좌표를 state에 등록
- customHook으로 관리 ( useGetGeolocation.jsx ) 
<br/>
메인페이지와 검색페이지 두곳에서 현재 위치 좌표가 필요하기 때문에 반복되는 로직을 관리하기 위해 커스텀훅으로 관리 했습니다 !
커스텀훅은 src/Hooks 폴더에서 관리합니다 :)
<br/>
> [#48] geolocation 이용하여 현재 위치 좌표 알아내기 

- src/Components/MyPage/MyReviews/MyReviews.js
- src/Components/MyPage/MyReviews/MyReviews.styles.js
- src/Components/MyPage/MyReviews/MyReviewsLayout.js
<br/>
- issue title  #12
<br/>
- 리뷰 수정완료 이후 재수정 / 수정취소 시에도 가장 최신 업데이트된 내용 유지
- 모바일 버전 디자인 수정
<br/>
<br/>
> [#12] feature/myPage/reviewList 리뷰수정 후 데이터 유지

- src/Components/Review/Review.jsx
- src/Components/Review/ReviewsList.jsx
- src/Components/Review/ReviewsList.styles.js
- src/Service/camps.js
<br/>
- issue title  #58    
<br/>
- 상세페이지 후기에서 유저가 작성한 리뷰에만 수정, 삭제가 렌더링
<br/>
<br/>
> #58 feat: 유저가 작성한 리뷰만 수정, 삭제 버튼이 렌더링

- src/Components/Review/ReviewsList.jsx
- src/Components/Review/ReviewsList.styles.js
- src/Service/camps.js
<br/>
- issue title  #60    
<br/>
- 리뷰 좋아요 디자인 변경
- 리뷰 좋아요 기능 구현
- 자신이 쓴 리뷰 좋아요 방지
<br/>
<br/>
> [#60]Feature/reviewLike 리뷰 좋아요 기능 및 UI

- src/Components/CampInformation/CampInformation.jsx
- src/Components/CampInformation/CampInformation.style.js
- src/Components/Main/MainCampRecommend/MainCampRecommend.js
- src/Components/Main/MainCampRecommend/MainCampRecommend.styles.js
- src/Components/MyPage/AlrimList/AlrimLayout.js
- src/Components/Notice/Notice.jsx
- src/Components/Notice/Notice.style.jsx
- src/Pages/DetailPage/DetailPage.jsx
<br/>
- issue title  
- #52 
- #57 
<br/>
[ 메인페이지 ] 
- PC와 모바일 각각 한 페이지에 표시되는 컨텐츠 갯수 구분
- 반응형 디자인 추가
- UI 수정 (캠핑장 좋아요 위치 변경)
[ 슬라이드 ]
- 슬라이드 레이아웃 오류 해결
- 슬라이드 프리뷰 기능
- 리뷰에 이미지가 있어야만 슬라이드에 렌더링 
<br/>
<br/>
> [#52] [#57] feature/slide 메인페이지 내 근처 캠핑장 추천 반응형디자인 & 슬라이드 기능 추가

- src/Components/auth/AuthProvider.js
- src/Pages/MyPage/MyPage.js
<br/>
- issue title  #65 
<br/>
- 로그인 안된 유저 마이페이지 접근 제한
- 로그아웃 시 localstorage.clear
<br/>
- useContext(UserContext)로 받은 user로 제한 하니 로그인된 유저도 튕겨서 localstorage로 했습니다.
<br/>
> [#65] Feature/onlyLoginAccess 로그인 안된 유저 마이페이지 접근 제한

- src/Components/Review/Review.jsx
- src/Components/Review/Review.style.js
- src/Components/Review/ReviewsList.jsx
- src/Pages/DetailPage/DetailPage.jsx
- src/Service/camps.js
<br/>
- issue title  #35  
<br/>
- 페이지 선택시 페이지 넘버에 맞는 데이터 요청
- 마이페이지 리뷰 페이지네이션 기능 구현
- 상세페이지 리뷰 페이지네이션 기능 구현
<br/>
- 한 페이지당 리뷰는 5개씩 렌더링됩니다 ! 이 부분은 변경이 가능하니 필요시 의견주세요 !
<br/>
> [#35] Feature/reviewPagination 리뷰 페이지네이션 기능 

- src/Components/SearchBar/SearchBar.jsx
- src/Components/SearchBar/SearchResult/SearchResult.jsx
- src/Components/SearchLocation/SearchLocation.jsx
- src/Pages/SearchPage/SearchPage.js
- src/Service/camps.js
- src/context/SearchPaginationContext.js
<br/>
- issue title  #35  
<br/>
- 검색페이지 페이지네이션 구현 완료
<br/>
- 페이지네이션 컴포넌트가 추가되면서 레이아웃이 아~주 약간 달라졌습니다 
<br/>
> [#35] feature/searchPagination 검색페이지 페이지네이션 구현

- src/Components/CampLike/CampLike.jsx
- src/Components/CampLike/CampLike.style.js
- src/Components/Review/Review.jsx
- src/Components/Review/ReviewsList.jsx
- src/Service/camps.js
<br/>
- issue title  #75   
<br/>
- 로그인한 유저가 아닌 경우 리뷰 제한 및 경고 메시지 렌더링 
- 리뷰 작성글 5글자 미만 제한 및 경고 메시지 렌더링 
- 별점 선택 안 할 경우 제한 및 경고 메시지 렌더링 
<br/>
없습니다 :)
<br/>
> [#75] Feature/reviewAlert 비유저 리뷰 좋아요, 리뷰 작성 글 5글자 미만, 별점 선택 안 할 경우 경고

- src/App.js
- src/Components/Navbar/Navbar.js
- src/Pages/CommunityPage/CommunityPage.jsx
<br/>
- issue title  #85  
<br/>
- 커뮤니티 페이지 이동시 개발 중이라고 알림 
- 메인페이지 이동 버튼 / 기능구현
<br/>
디자인을 우선 임의로 해봤는데 어떠신가요 ?! 확인하시고 코멘트 달아주세요 ㅎㅎ 
<br/>
> [#85] Feature/community 커뮤니티 페이지 이동시 개발중이라고 알림

- src/Components/Navbar/Navbar.js
- src/Components/Navbar/Navbar.styles.js
<br/>
- issue title  #92     
<br/>
- 모바일 뱃지 위치 수정
<br/>
<br/>
> [#92]Feature/mobileCloseMenu 모바일 뱃지 위치 수정

- src/Components/Review/ReviewsList.jsx
- src/Pages/DetailPage/DetailPage.jsx
<br/>
- issue title  #94      
<br/>
- ReviewList, DetailPage에서 allowHalf props 제거
<br/>
<br/>
> [#94] feature/rateStar allowHalf props 제거

- src/Components/Review/Review.style.js
- src/Components/Review/ReviewsList.jsx
- src/Components/Review/ReviewsList.styles.js
<br/>
- issue title  #96       
<br/>
- 모바일 작성, 수정완료버튼 디자인 깨짐현상 수정
- 좋아요 모바일 디자인 수정
- customHook을 사용하여 datetype 변환
<br/>
<br/>
> [#96]Feature/reviewMobileDesign 모바일 리뷰컴포넌트 디자인 수정

- src/Components/Review/ReviewsList.styles.js
<br/>
- issue title  #102        
<br/>
- 텍스트 길어질 때 review 스타일 수정
- 더보기 / 간략히 토글
<br/>
없습니다 !
<br/>
> [#102]Feature/reviewStyle 텍스트 길어질 때 review 스타일 수정

- src/Components/Review/Review.jsx
- src/Components/Review/ReviewsList.jsx
- src/Components/Review/ReviewsList.styles.js
<br/>
- issue title  #104         
<br/>
-  리뷰 길이 계산하여 state 변경
- 더보기 버튼 기능
- 접기 버튼 기능
<br/>
없습니다 !
<br/>
> [#104] Feature/readMore 리뷰 길이에 따라 더보기, 접기 버튼 활성화

- README.md
- src/components/review/reveiwList/ReviewsList.jsx
- src/components/review/reveiwList/reviewsList.styles.js
- src/pages/myPage/MyPage.jsx
- src/pages/searchPage/searchBar/SearchBar.jsx
- src/pages/searchPage/searchBar/resultList/ResultList.jsx
- src/pages/searchPage/searchBar/resultList/ResultList.style.js
- src/pages/searchPage/searchBar/searchResult/searchResult/SearchResult.jsx
- src/pages/searchPage/searchBar/searchResult/searchResult/searchResult.style.js
- src/service/api.js
<br/>
- issue title #108          
<br/>
-  베스트리뷰 좋아요 버튼 레이아웃 깨짐 해결
-  리뷰에 더보기 버튼 누르면 레이아웃 깨짐 해결
- 마이페이지 리뷰 이미지 크기 수정
-  정렬 좋아요순 -> 별점순으로 변경
<br/>
없습니다 !
<br/>
> [#108] Feature/layoutRefactor  레이아웃 리팩토링 및 정렬 별점순으로 수정

- src/App.js
- src/pages/communityPage/CommunityPage.jsx
- src/pages/communityPage/CommunityPage.style.js
- src/pages/communityPage/category/CommunityAllPost.js
- src/pages/communityPage/category/CommunityCategory.style.js
- src/pages/communityPage/category/CommunityPicture.js
- src/pages/communityPage/category/CommunityQnA.js
- src/pages/communityPage/category/CommunityTalk.js
- src/pages/communityPage/writePage/WritePage.jsx
<br/>
- issue title #115          
<br/>
- 커뮤니티 페이지 탭메뉴 UI
- 커뮤니티 writePage 추가
- 공통 UI(각 탭메뉴 클릭 시 보이는 페이지) 및 반응형 스타일 추가
<br/>
베스트 게시글 슬라이드 부분에 대한 협의가 끝나지 않아서 구조만 잡아두었습니다!
<br/>
> [#115]Feature/communityRoute 커뮤니티 페이지 UI

- .github/workflows/deploy.yml
<br/>
- issue title .
<br/>
step에 run 추가하였습니다 .
```
- name: Deploy
run: echo "🏃‍♂️ start deploying! "
run: npm deploy
```
<br/>
<br/>
> fix: GithubAction 세팅 에러해결

- .github/workflows/deploy.yml
<br/>
- issue title 
<br/>
echo 의 run을 Deploy위로 분리 하였습니다.
```
steps:
- name: Checkout source code.
uses: actions/checkout@v2
- run: echo "🏃‍♂️ start deploying! "
- name: Deploy
run: npm deploy
```
<br/>
<br/>
> fix: GithubAction run 분리

- .github/workflows/deploy.yml
<br/>
- issue title 
<br/>
npm build:dev 에서 에러 발생 하여 npm build로 변경하였습니다. 
```
- name: Build
run: npm build
```
<br/>
<br/>
> fix: npm build:dev -> npm build로 변경

- .github/workflows/deploy.yml
<br/>
<br/>
Unable to locate credentials에러가 발생했습니다.
자격 증명을 찾을 수 없는 에러이기 때문에 아래와 같이 코드 수정을 했습니다.
```
- name: Configure AWS Credentials
uses: aws-actions/configure-aws-credentials@v1
with:
aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
aws-region: ${{ secrets.AWS_REGION }}
- name: Deploy to S3
run: aws s3 sync ./dist s3://${{ secrets.DEV_AWS_S3_BUCKET }} --delete
- name: Invalidate CloudFront Cache
run: aws cloudfront create-invalidation --distribution-id ${{secrets.DEV_AWS_DISTRIBUTION_ID}} --paths "/*"
```
<br/>
- 참고사항 기재
<br/>
> fix:  Unable to locate credentials 에러 해결을 위해 수정

- .github/workflows/deploy.yml
<br/>
<br/>
cloudfront cache 제거
<br/>
<br/>
> fix: cloudfront cache 제거

- .github/workflows/deploy.yml
<br/>
<br/>
yml 파일 내에 env 파일 선언 위치 변경
<br/>
<br/>
> fix: yml 파일 env 수정

- src/components/campLike/CampLike.jsx
- src/pages/searchPage/searchBar/SearchBar.jsx
- src/pages/searchPage/searchBar/resultList/ResultList.jsx
- src/pages/searchPage/searchBar/resultList/ResultList.style.js
- src/service/api.js
<br/>
- issue title #120           
<br/>
- 검색페이지 검색결과 리스트 좋아요 기능 추가
- 검색결과 리스트 description 행간 및 text-overflow 추가
<br/>
merge conflict나서 사라졌던 별점 초기화 코드 SearchBar.jsx에 추가된 것도 포함되어 있습니다.
<br/>
> [#120] feature/searchListLike 검색페이지 검색결과 리스트 좋아요 기능 추가

- src/components/notice/Notice.jsx
- src/pages/communityPage/communityDetailPage/CommunityDetailPage.jsx
- src/pages/communityPage/communityDetailPage/postComments/PostComments.jsx
- src/pages/communityPage/communityDetailPage/postComments/PostComments.style.js
- src/pages/communityPage/communityDetailPage/postComments/commentList/CommentList.jsx
- src/pages/communityPage/communityDetailPage/postComments/commentList/CommentList.style.js
<br/>
- issue title #114 
<br/>
- 커뮤니티 게시글의 댓글 없을 시 notice 컴포넌트 렌더링
- 댓글 작성 UI
- 댓글 수정 UI
- 댓글 목록 UI
<br/>
- 수정, 삭제, 더보기 기능은 API 완료되면 추가로 작업할 예정입니다.
- whimsical 대로 textarea를 100%로 채우고 버튼을 내리는게 나을지.. 디자인 피드백 부탁드립니다!
<br/>
> [#114]Feature/comment

- src/pages/searchPage/searchBar/SearchBar.jsx
- src/pages/searchPage/searchBar/searchBar.style.js
<br/>
- issue title #142 
<br/>
- 검색페이지 검색내용 전체 초기화
- 모바일에 전체 초기화 기능 및 디자인
<br/>
<br/>
> [#142] feature/reset 검색페이지 검색내용 전체 초기화

- src/pages/communityPage/communityDetailPage/CommunityDetailPage.jsx
- src/pages/communityPage/communityDetailPage/postComments/PostComments.jsx
- src/pages/communityPage/communityDetailPage/postComments/commentList/CommentList.jsx
- src/pages/communityPage/communityDetailPage/postComments/commentList/CommentList.style.js
- src/service/api.js
<br/>
- issue title #114 
<br/>
- 댓글 목록 조회 및 페이지네이션
- 댓글 등록
- 댓글 작성자만 댓글 수정
- 댓글 작성자만 댓글 삭제
- 해당 게시글의 작성자가 댓글 작성 시 [작성자]표시
- 댓글의 말줄임표 제거
<br/>
- 없습니다! 수정사항 있으면 알려주세요
<br/>
> [#114]Feature/comment 커뮤니티 게시글 댓글

- src/components/bestPost/bestPostSliderList/BestPostSliderList.jsx
- src/components/bestPost/bestPostSliderList/bestPostSliderList.style.js
- src/components/modal/authModal/AuthModal.jsx
- src/components/modal/authModal/AuthModal.style.js
- src/service/firebaseAuth.js
<br/>
- issue title #150
- - issue title #113
<br/>
- 베스트 게시글 슬라이더에서 회원이 좋아요한 게시글 liked response를 받아 좋아요 한 게시글이면 좋아요 표시 
- 모달 디자인 변경
- Github, Facebook OAuth 추가 
<br/>
<br/>
> [#150 #113] feat: 슬라이더에 회원이 좋아요한 게시글 좋아요 표시, 모달 OAuth 추가

- src/service/api.js
<br/>
<br/>
- api 파일 내에 ServerUrl 추가
<br/>
<br/>
> build: 배포를 위한 api 파일 ServerUrl 추가

- README.md
- src/components/communityPost/CommunityPost.jsx
<br/>
- issue title # issue number
<br/>
- 변경사항 기재
<br/>
- 참고사항 기재
<br/>
> README 파일에 아키텍쳐 및 ERD 이미지 추가
